image: node:alpine # Much smaller than other variants, faster and more resource effective

stages:
  - install_dependencies
  - build_project

cache:
  key: "${CI_COMMIT_REF_SLUG}" # Branch-specific cache keys to have separate caches across branches.
  paths:
    - node_modules/

install_dependencies:
  stage: install_dependencies
  script:
    - npm ci

build_project:
  stage: build_project
  script:
    - npm run build
