image: node:alpine # Much smaller than other variants, faster and more resource effective

stages:
  - install
  - build

cache:
  key: "${CI_COMMIT_REF_SLUG}" # Branch-specific cache keys to have separate caches across branches.
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install

build_project:
  stage: build
  script:
    - npm run build
