image: node:alpine # Much smaller than other variants, faster and more resource effective

stages:
  - install_dependencies
  - lint
  - build_project

cache:
    key: "${CI_COMMIT_REF_SLUG}" # Branch-specific cache keys to have separate caches across branches.
    paths:
    - node_modules/

install_dependencies:
  stage: install_dependencies
  script:
    - apk add --no-cache git # For instances where installations require git
    - npm ci --prefer-offline  # --prefer-offline to make it prefer using locally cached packages rather than downloading

lint:
  stage: lint
  script:
    - npm run lint    
  allow_failure: true  

build_project:
  stage: build_project
  script:
    - npm run build

